### ISSUE TITLE
spamassassin not working

### ISSUE THREAD

**Issue by mzummo** [gurnadi/sentraMail#1]
spam assassin spam headers not showing and spam filtering not working

**Comment by gurnadi** [comment]
Could you send your amavisd.conf? Ensure that clamd.amavisd running on your server.

**Comment by mzummo** [comment]
@gurnadi i have the default config with just a few minor changes (did a fresh install as well just to make sure and still not working)

**Comment by mzummo** [comment]
@gurnadi can i send my config via email to you (would rather not have that on the internet)

**Comment by gurnadi** [comment]
please send it to gurnadi[at]gmail[dot]com

**Comment by mzummo** [comment]
@gurnadi was there a patch released to fix this issue? I havent had the chance to test the script again, I have set something up on debian since and have everything working (with rspamd and spamassiassin)

**Comment by gurnadi** [comment]
Since you re not sending your configuration, i can not reproduce the bugs. Tested on centos 6 works without any problem. So, i wont release a patch (yet)

**Comment by mzummo** [comment]
that's fair, (i was testing on a clean install of 6.8 myself ... I was expecting to see spam scores in the headers instead of just saying it was scanned ... at any including - flag sa_ levels). When I get a chance again to install the script I will send over the config and logs, perhaps I could be in error ... I like this script and vimbadmin (and would love to see a centos 7 version too) ...

**Comment by gurnadi** [comment]
Please take a look in the amavisd.conf, you will see this line:

$sa_tag_level_deflt  = -999;  # add spam info headers if at, or above that level

if you put the number "-999" and then restart amavisd then you will see spam scores in the headers.

i'm not having a time yet to modifying this script for centos 7.
